# Generated by Django 4.2.4 on 2023-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_price_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_new',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
