# Generated by Django 4.2.4 on 2023-08-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_price_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_new',
        ),
    ]
