# Generated by Django 4.2.4 on 2023-08-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='discount_images')),
            ],
            options={
                'verbose_name': 'Discount Category',
                'verbose_name_plural': 'Discount Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('discount_persentage', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('heart', models.IntegerField(default=0)),
                ('retweet', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.discount_category')),
            ],
            options={
                'verbose_name': 'Discount Product',
                'verbose_name_plural': 'Discount_Products',
            },
        ),
    ]
