# Generated by Django 4.2.4 on 2023-08-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_discount_category_discount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_time',
            field=models.IntegerField(default=1),
        ),
    ]
