# Generated by Django 4.2.4 on 2023-08-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_shipping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
