# Generated by Django 4.2.4 on 2023-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_product',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
