# Generated by Django 4.2.4 on 2023-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_discount_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='discount_product',
            name='slug',
            field=models.SlugField(default='a'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='a'),
        ),
    ]
