# Generated by Django 4.2.4 on 2023-08-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_options_discount_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
