# Generated by Django 4.2.4 on 2023-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_discount_product_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='a'),
        ),
    ]
