# Generated by Django 4.2.4 on 2023-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
