# Generated by Django 4.2.4 on 2023-11-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='title',
            new_name='email',
        ),
    ]
