# Generated by Django 4.2.4 on 2023-11-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_title_subscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='title',
        ),
    ]
