# Generated by Django 4.2.4 on 2023-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_email_subscriber_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='title',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
